FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build

COPY . /source
WORKDIR /source/backend

ARG TARGETARCH

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet publish -a ${TARGETARCH/amd64/x64} --use-current-runtime --self-contained false -o /app

# ---- Final stage ----
FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
WORKDIR /app

# Install runtime dependencies
RUN apk add --no-cache krb5-libs icu-libs libgcc libstdc++

# Copy published app
COPY --from=build /app .

# Copy migrations after publishing to avoid overwriting
COPY backend/Migrations/ ./Migrations/

# Switch to non-privileged user
USER $APP_UID

ENTRYPOINT ["dotnet", "backend.dll"]
