# --- Build Stage ---
FROM node:22-alpine AS builder

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install --production=false

COPY ./frontend .
RUN npm run build

# --- Production Stage ---
FROM node:22-alpine

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install --production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "start"]